import * as React from 'react';
import Pagination from '@mui/material/Pagination';
import Stack from '@mui/material/Stack';
import { Typography } from '@mui/material';

export default function MuiPagination() {
   const [page, setPage] = React.useState(2);
   const [rowsPerPage, setRowsPerPage] = React.useState(5);
console.log(page)
   return (
      <Stack spacing={2}>
         <Pagination
            count={10}
            page={page}
            variant="outlined"
            shape="rounded"
            onChange={(event, currentPage) => setPage(currentPage)}
         />

         {tableData.map((row, index) => {
            return (
               <Typography key={index}>
                  {index + 1} - {row.first_name}
               </Typography>
            );
         })}
      </Stack>
   );
}


const tableData = [
   {
      id: 1,
      first_name: 'Kaila',
      last_name: 'Bunclark',
      email: 'kbunclark0@adobe.com',
      gender: 'Female',
      ip_address: '233.111.38.150',
   },
   {
      id: 2,
      first_name: 'Debera',
      last_name: 'Wolver',
      email: 'dwolver1@sina.com.cn',
      gender: 'Female',
      ip_address: '98.155.37.35',
   },
   {
      id: 3,
      first_name: 'Horten',
      last_name: 'Dingley',
      email: 'hdingley2@mozilla.org',
      gender: 'Male',
      ip_address: '175.14.78.70',
   },
   {
      id: 4,
      first_name: 'Leonidas',
      last_name: 'Peterffy',
      email: 'lpeterffy3@odnoklassniki.ru',
      gender: 'Male',
      ip_address: '248.68.52.39',
   },
   {
      id: 5,
      first_name: 'Saunders',
      last_name: 'Lowy',
      email: 'slowy4@sogou.com',
      gender: 'Male',
      ip_address: '14.8.19.5',
   },
   {
      id: 6,
      first_name: 'Marcus',
      last_name: 'McHale',
      email: 'mmchale5@stanford.edu',
      gender: 'Male',
      ip_address: '110.61.241.166',
   },
   {
      id: 7,
      first_name: 'Jolie',
      last_name: 'Sambles',
      email: 'jsambles6@mozilla.com',
      gender: 'Female',
      ip_address: '247.171.11.33',
   },
   {
      id: 8,
      first_name: 'Joey',
      last_name: 'Stoneman',
      email: 'jstoneman7@pagesperso-orange.fr',
      gender: 'Male',
      ip_address: '61.58.239.240',
   },
   {
      id: 9,
      first_name: 'Reginauld',
      last_name: 'Warner',
      email: 'rwarner8@youtube.com',
      gender: 'Male',
      ip_address: '71.249.115.155',
   },
   {
      id: 10,
      first_name: 'Leeanne',
      last_name: 'Gifford',
      email: 'lgifford9@jimdo.com',
      gender: 'Female',
      ip_address: '254.186.76.195',
   },
   {
      id: 11,
      first_name: 'Nobie',
      last_name: 'Montacute',
      email: 'nmontacutea@cyberchimps.com',
      gender: 'Male',
      ip_address: '200.15.85.140',
   },
   {
      id: 12,
      first_name: 'Patrizio',
      last_name: 'Hast',
      email: 'phastb@wordpress.org',
      gender: 'Male',
      ip_address: '140.43.110.20',
   },
   {
      id: 13,
      first_name: 'Kenon',
      last_name: 'Moncey',
      email: 'kmonceyc@google.com.br',
      gender: 'Male',
      ip_address: '239.234.218.201',
   },
   {
      id: 14,
      first_name: 'Ellary',
      last_name: 'Angrock',
      email: 'eangrockd@4shared.com',
      gender: 'Male',
      ip_address: '225.217.91.117',
   },
   {
      id: 15,
      first_name: 'Billy',
      last_name: 'Robelow',
      email: 'brobelowe@ft.com',
      gender: 'Male',
      ip_address: '80.199.145.110',
   },
   {
      id: 16,
      first_name: 'Lenard',
      last_name: 'Eberle',
      email: 'leberlef@altervista.org',
      gender: 'Male',
      ip_address: '125.169.45.142',
   },
   {
      id: 17,
      first_name: 'Vachel',
      last_name: 'Doole',
      email: 'vdooleg@last.fm',
      gender: 'Male',
      ip_address: '195.171.235.15',
   },
   {
      id: 18,
      first_name: 'Edik',
      last_name: 'Batrim',
      email: 'ebatrimh@gizmodo.com',
      gender: 'Male',
      ip_address: '254.119.243.17',
   },
   {
      id: 19,
      first_name: 'Vivianna',
      last_name: 'Stonier',
      email: 'vstonieri@cmu.edu',
      gender: 'Female',
      ip_address: '109.90.222.52',
   },
   {
      id: 20,
      first_name: 'Wood',
      last_name: 'Ivanchenkov',
      email: 'wivanchenkovj@fotki.com',
      gender: 'Male',
      ip_address: '33.41.97.161',
   },
   {
      id: 21,
      first_name: 'Britte',
      last_name: 'Wimlet',
      email: 'bwimletk@studiopress.com',
      gender: 'Female',
      ip_address: '74.217.43.246',
   },
   {
      id: 22,
      first_name: 'Carissa',
      last_name: 'Henryson',
      email: 'chenrysonl@ucoz.ru',
      gender: 'Female',
      ip_address: '79.151.55.100',
   },
   {
      id: 23,
      first_name: 'Daren',
      last_name: 'Dagg',
      email: 'ddaggm@wired.com',
      gender: 'Genderqueer',
      ip_address: '98.241.187.103',
   },
   {
      id: 24,
      first_name: 'Web',
      last_name: 'McBayne',
      email: 'wmcbaynen@samsung.com',
      gender: 'Male',
      ip_address: '57.98.214.115',
   },
   {
      id: 25,
      first_name: 'Coreen',
      last_name: 'Adicot',
      email: 'cadicoto@php.net',
      gender: 'Female',
      ip_address: '111.223.231.134',
   },
   {
      id: 26,
      first_name: 'Essie',
      last_name: 'Shillitoe',
      email: 'eshillitoep@ebay.com',
      gender: 'Female',
      ip_address: '168.238.179.54',
   },
   {
      id: 27,
      first_name: 'Klement',
      last_name: 'Swainsbury',
      email: 'kswainsburyq@answers.com',
      gender: 'Male',
      ip_address: '15.63.108.118',
   },
   {
      id: 28,
      first_name: 'Beverly',
      last_name: 'Flatt',
      email: 'bflattr@wufoo.com',
      gender: 'Polygender',
      ip_address: '14.171.251.253',
   },
   {
      id: 29,
      first_name: 'Kyle',
      last_name: 'Gerritzen',
      email: 'kgerritzens@behance.net',
      gender: 'Male',
      ip_address: '208.152.211.88',
   },
   {
      id: 30,
      first_name: 'Ame',
      last_name: 'Lintill',
      email: 'alintillt@quantcast.com',
      gender: 'Female',
      ip_address: '24.82.197.14',
   },
   {
      id: 31,
      first_name: 'Earl',
      last_name: 'Garrett',
      email: 'egarrettu@auda.org.au',
      gender: 'Agender',
      ip_address: '163.245.51.59',
   },
   {
      id: 32,
      first_name: 'Michell',
      last_name: 'Commucci',
      email: 'mcommucciv@hao123.com',
      gender: 'Female',
      ip_address: '240.180.188.184',
   },
   {
      id: 33,
      first_name: 'Matthias',
      last_name: 'Silbermann',
      email: 'msilbermannw@intel.com',
      gender: 'Male',
      ip_address: '98.128.92.251',
   },
   {
      id: 34,
      first_name: 'Steward',
      last_name: 'Dary',
      email: 'sdaryx@unesco.org',
      gender: 'Genderfluid',
      ip_address: '142.110.176.33',
   },
   {
      id: 35,
      first_name: 'Mose',
      last_name: 'Bassett',
      email: 'mbassetty@friendfeed.com',
      gender: 'Bigender',
      ip_address: '115.112.226.208',
   },
   {
      id: 36,
      first_name: 'Jena',
      last_name: 'Harty',
      email: 'jhartyz@mlb.com',
      gender: 'Female',
      ip_address: '170.198.247.129',
   },
   {
      id: 37,
      first_name: 'Nobe',
      last_name: 'Pitchers',
      email: 'npitchers10@ebay.co.uk',
      gender: 'Male',
      ip_address: '141.39.144.65',
   },
   {
      id: 38,
      first_name: 'Vic',
      last_name: 'Tytcomb',
      email: 'vtytcomb11@mayoclinic.com',
      gender: 'Male',
      ip_address: '80.229.81.234',
   },
   {
      id: 39,
      first_name: 'Gabbie',
      last_name: 'Brickdale',
      email: 'gbrickdale12@ning.com',
      gender: 'Female',
      ip_address: '72.13.255.7',
   },
   {
      id: 40,
      first_name: 'Steffane',
      last_name: 'McClay',
      email: 'smcclay13@google.de',
      gender: 'Female',
      ip_address: '72.159.205.183',
   },
   {
      id: 41,
      first_name: 'Zackariah',
      last_name: 'Parris',
      email: 'zparris14@google.com.br',
      gender: 'Male',
      ip_address: '249.146.48.156',
   },
   {
      id: 42,
      first_name: 'Dulcine',
      last_name: 'Fosserd',
      email: 'dfosserd15@sourceforge.net',
      gender: 'Female',
      ip_address: '105.7.128.97',
   },
   {
      id: 43,
      first_name: 'Grant',
      last_name: 'Faveryear',
      email: 'gfaveryear16@mozilla.com',
      gender: 'Genderfluid',
      ip_address: '129.208.229.6',
   },
   {
      id: 44,
      first_name: 'Ely',
      last_name: 'Euels',
      email: 'eeuels17@google.com',
      gender: 'Male',
      ip_address: '124.211.29.248',
   },
   {
      id: 45,
      first_name: 'Ardyce',
      last_name: 'Spellacey',
      email: 'aspellacey18@jiathis.com',
      gender: 'Female',
      ip_address: '238.191.184.233',
   },
   {
      id: 46,
      first_name: 'Marcille',
      last_name: 'Stockman',
      email: 'mstockman19@gravatar.com',
      gender: 'Genderfluid',
      ip_address: '114.39.69.92',
   },
   {
      id: 47,
      first_name: 'Florence',
      last_name: 'Stickler',
      email: 'fstickler1a@mayoclinic.com',
      gender: 'Female',
      ip_address: '245.164.169.4',
   },
   {
      id: 48,
      first_name: 'Reta',
      last_name: 'Garment',
      email: 'rgarment1b@sbwire.com',
      gender: 'Female',
      ip_address: '181.229.140.202',
   },
   {
      id: 49,
      first_name: 'Sammy',
      last_name: 'Hindrich',
      email: 'shindrich1c@cnet.com',
      gender: 'Male',
      ip_address: '129.24.53.7',
   },
   {
      id: 50,
      first_name: 'Valentine',
      last_name: 'Rime',
      email: 'vrime1d@sakura.ne.jp',
      gender: 'Female',
      ip_address: '144.244.169.201',
   },
];
